### ISSUE TITLE
Invalid constructor parameters

### ISSUE THREAD

**Issue by maxime-paquatte** [Invenietis/yodii#2]
Hello,

I did not understand the plugin mechanisme the first time. So I tried this :

>        public MyPluginA(MyPluginB b)
>        {
>        }

The result was a `TargetParameterCountException`, It would be nice to have a more explicit message like `Plugin reference must be an Interface which extends IYodiiService`

Thanks

**Comment by olivier-spinelli** [comment]
This is now fixed.
